todo1 = TodoList.create(name: 'Setup Rails Application')
todo2 = TodoList.create(name: 'Setup Docker PG database')
TodoList.create(name: 'Create todo_lists table')
TodoList.create(name: 'Create TodoList model')
TodoList.create(name: 'Create TodoList controller')

todo1.items.create(title: 'Item1', description: 'Description for Item1')
todo1.items.create(title: 'Item2', description: 'Description for Item2')
todo1.items.create(title: 'Item3', description: 'Description for Item3')
todo2.items.create(title: 'Item1', description: 'Description for Item1')
todo2.items.create(title: 'Item2', description: 'Description for Item2')
todo2.items.create(title: 'Item3', description: 'Description for Item3')
